apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sentinel-ingress
  namespace: sentinel
  labels:
    app: sentinel
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/limit-rps: "10"
    nginx.ingress.kubernetes.io/limit-connections: "50"
    nginx.ingress.kubernetes.io/proxy-body-size: "1m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "60"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "60"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      add_header X-Frame-Options DENY always;
      add_header X-Content-Type-Options nosniff always;
      add_header X-XSS-Protection "1; mode=block" always;
      add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - sentinel.example.com
    secretName: sentinel-tls
  rules:
  - host: sentinel.example.com
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: sentinel-app-service
            port:
              number: 3000
      - path: /metrics
        pathType: Prefix
        backend:
          service:
            name: sentinel-app-service
            port:
              number: 3000
      - path: /health
        pathType: Prefix
        backend:
          service:
            name: sentinel-app-service
            port:
              number: 3000
      - path: /dashboard
        pathType: Prefix
        backend:
          service:
            name: sentinel-dashboard-service
            port:
              number: 3001
      - path: /
        pathType: Prefix
        backend:
          service:
            name: sentinel-dashboard-service
            port:
              number: 3001

---
apiVersion: v1
kind: Secret
metadata:
  name: sentinel-secrets
  namespace: sentinel
  labels:
    app: sentinel
type: Opaque
stringData:
  webhook-url: "https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK"
  dashboard-auth: "admin:dashboard123"
  api-key: "your-api-key-here"

---
apiVersion: v1
kind: Secret
metadata:
  name: sentinel-tls
  namespace: sentinel
  labels:
    app: sentinel
type: kubernetes.io/tls
data:
  # Base64 encoded TLS certificate and key
  # Replace with your actual certificate data
  tls.crt: LS0tLS1CRUdJTi... # Your certificate here
  tls.key: LS0tLS1CRUdJTi... # Your private key here